# Generated by Django 2.2.6 on 2020-01-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [

        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('ingredients', models.TextField()),
                ('description', models.TextField()),
                ('how_to_prepare', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('preparation_time', models.SmallIntegerField()),
                ('votes', models.IntegerField(default=True)),
            ],
        ),
    ]
