# Generated by Django 2.2.6 on 2020-01-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0004_auto_20200116_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipeplan',
            name='meal_name',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='recipeplan',
            name='order',
            field=models.SmallIntegerField(unique=True),
        ),
    ]
