# Generated by Django 2.2.6 on 2020-01-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0005_auto_20200116_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeplan',
            name='meal_name',
            field=models.CharField(max_length=32),
        ),
    ]
