# Generated by Django 2.2.6 on 2020-01-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jedzonko', '0006_auto_20200117_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeplan',
            name='order',
            field=models.SmallIntegerField(),
        ),
    ]
